apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.23.0
      command:
        - /busybox/cat
      tty: true
      resources:
        limits:
          cpu: "1000m"
          memory: "1024Mi"
