apiVersion: v1
kind: Pod
spec:
  containers:
    - name: rust
      image: docker.io/library/rust:1.75-buster
      command:
        - cat
      tty: true
      resources:
        limits:
          cpu: "1000m"
          memory: "2048Mi"
